info:
  name: deleteConfig
  type: http
  seq: 4

http:
  method: DELETE
  url: "{{url}}/api/v1/agents/{{id_agent}}/config/{{key}}"
  auth: inherit

runtime:
  variables:
    - name: id_agent
      value: 91f76f63-5bde-4aa9-837a-f6bccab6d624
    - name: key
      value: save_messages

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
